import 'package:flangapp_app/enum/action_type.dart';
import 'package:flangapp_app/models/navigation_item.dart';

import '../enum/background_mode.dart';
import '../enum/load_indicator.dart';
import '../enum/template.dart';

class Config {

  /// Generated by SiteNative 29-07-2022 20:16:50
  /// App UID: 24c2f20c-4c2b-aa6c-c5fa-9e64bcbb73ce
  /// Version: https://app.bynet.host/backend/
  /// API server: {VERSION}

  /// *** App config *** ///
  // App name
  static String appName = "Japan";
  // App link
  static String appLink = "https://bistro-japan.ru/menu/?app=yes";
  // Display page name without app name (after 1 page)
  static bool displayTitle = false;
  // Main color (any HEX color)
  static String color = "#222222";
  // Active color (any HEX color)
  static String activeColor = "#666666";
  // Icon color color (any HEX color)
  static String iconColor = "#222222";
  // Title color (true - white, false - black)
  static bool isDark = true;
  // Pull to refresh enabled
  static bool pullToRefresh = false;
  // User agent
  static String userAgent = "";
  // Admin email
  static String appEmail = "sz@bynet.host";
  // Template
  static Template appTemplate = Template.drawer;
  // Loading indicator style
  static LoadIndicator indicator = LoadIndicator.spinner;
  // Loading indicator color
  static String indicatorColor = "#167B8F";

  /// *** Access ** ///
  // Access to camera
  static bool accessCamera = false;
  // Access to microphone
  static bool accessMicrophone = false;
  // Access to geolocation
  static bool accessLocation = false;

  /// *** Drawer settings *** ///
  // Title
  static String drawerTitle = "Меню";
  // Subtitle
  static String drawerSubtitle = "";
  // Background mode
  static BackgroundMode drawerBackgroundMode = BackgroundMode.color;
  // Background color (any HEX color)
  static String drawerBackgroundColor = "#222222";
  // Title color (true - white, false - black)
  static bool drawerIsDark = true;
  // Background image name
  static String drawerBackgroundImage = "drawer_background.png";
  // Logo image name
  static String drawerLogoImage = "logo.png";
  // Display logo
  static bool drawerIsDisplayLogo = false;

  /// *** Splashscreen settings *** ///
  // Background color (any HEX color)
  static String splashBackgroundColor = "#000000";
  // Text color (any HEX color)
  static String splashTextColor = "#ffffff";
  // Is image background
  static bool splashIsBackgroundImage = false;
  // Background image name
  static String splashBackgroundImage = "splash_screen.png";
  // Tagline
  static String splashTagline = "";
  // Delay display (seconds)
  static int splashDelay = 3;
  // Logo image name
  static String splashLogoImage = "splash_logo.png";
  // Display logo
  static bool splashIsDisplayLogo = true;

  /// *** PUSH OneSignal settings *** ///
  // App ID
  static String osAppID = "";
  // Signing
  static String osSigning = "3225dbc86664874481b014393d5e0dbb6315e0ebeabb05875323f14a42cd724a";
  // Enabled android?
  static bool osAndroidEnabled = false;

  /// *** Website styles *** ///
  // List div for hide in app
  static List<String> cssHideBlock = [];

  /// *** Localization *** ///
  // Name offline image
  static String offlineImage = "wifi.png";
  // Error internet connection (offline)
  static String messageErrorOffline = "No internet connection";
  // Error open web page
  static String messageErrorBrowser = "Failed to load the page. Please try again later!";
  // Name error page image
  static String errorBrowserImage = "error.png";
  // Title about exit from app (Android)
  static String titleExit = "Confirmation";
  // Message about exit from app (Android)
  static String messageExit = "Are you sure you want to exit the app?";
  // Confirm button about
  static String actionYesDownload = "Yes";
  // Cancel button
  static String actionNoDownload = "No";
  // Contact us email (About screen)
  static String contactBtn = "Contact us with email";
  // Back
  static String backBtn = "Go back";

  /// *** Navigation *** ///
  // Main app navigation
  static List<NavigationItem> mainNavigation = [
    	NavigationItem(name: "Бизнес ланч",icon: "apps-outline.svg",type: ActionType.internal,value: "https://bistro-japan.ru/menu/biznes-lanch/?app=yes",),
	NavigationItem(name: "Сеты",icon: "apps-outline.svg",type: ActionType.internal,value: "https://bistro-japan.ru/menu/seti/?app=yes",),
	NavigationItem(name: "Роллы",icon: "apps-outline.svg",type: ActionType.internal,value: "https://bistro-japan.ru/menu/rolli/?app=yes",),
	NavigationItem(name: "Горячие роллы",icon: "apps-outline.svg",type: ActionType.internal,value: "https://bistro-japan.ru/menu/goryachie-rolli/?app=yes",),
	NavigationItem(name: "Запеченные роллы",icon: "apps-outline.svg",type: ActionType.internal,value: "https://bistro-japan.ru/menu/zapechenie-rolli/?app=yes",),
	NavigationItem(name: "Хосомаки",icon: "apps-outline.svg",type: ActionType.internal,value: "https://bistro-japan.ru/menu/hosomaki/?app=yes",),
	NavigationItem(name: "Суши гунканы",icon: "apps-outline.svg",type: ActionType.internal,value: "https://bistro-japan.ru/menu/sushi-gunkanyi/?app=yes",),
	NavigationItem(name: "Поке",icon: "apps-outline.svg",type: ActionType.internal,value: "https://bistro-japan.ru/menu/poke/?app=yes",),
	NavigationItem(name: "Горячее",icon: "apps-outline.svg",type: ActionType.internal,value: "https://bistro-japan.ru/menu/goryachee/?app=yes",),
	NavigationItem(name: "Супы",icon: "apps-outline.svg",type: ActionType.internal,value: "https://bistro-japan.ru/menu/supy/?app=yes",),
	NavigationItem(name: "Соусы и добавки",icon: "apps-outline.svg",type: ActionType.internal,value: "https://bistro-japan.ru/menu/sousi-i-dobavki/?app=yes",),
	NavigationItem(name: "Напитки",icon: "apps-outline.svg",type: ActionType.internal,value: "https://bistro-japan.ru/menu/napitki/?app=yes",),
	NavigationItem(name: "Корзина",icon: "basket-outline.svg",type: ActionType.internal,value: "https://bistro-japan.ru/basket/?app=yes",),

  ];
  // Bar app navigation
  static List<NavigationItem> barNavigation = [
    
  ];
  // Modal navigation
  static List<NavigationItem> modalNavigation = [
    
  ];
}